### ISSUE TITLE
jdk 12，报错

### ISSUE THREAD

**Issue by p0mp0k0** [jhunters/jprotobuf#114]
jdk 12, 报错
Caused by: java.lang.IllegalStateException: Compilation failed. class: com.baidu.bjf.remoting.protobuf.descriptor.FileDescriptorProtoPOJO$$JProtoBufClass, diagnostics: [错误: 不再支持源选项 6。请使用 7 或更高版本。, 错误: 不再支持目标选项 6。请使用 7 或更高版本。]
	at com.baidu.bjf.remoting.protobuf.utils.compiler.JdkCompiler.doCompile(JdkCompiler.java:164) ~[jprotobuf-2.2.11.jar:na]
	at com.baidu.bjf.remoting.protobuf.utils.compiler.AbstractCompiler.compile(AbstractCompiler.java:43) ~[jprotobuf-2.2.11.jar:na]
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.doCreate(ProtobufProxy.java:392) ~[jprotobuf-2.2.11.jar:na]
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:274) ~[jprotobuf-2.2.11.jar:na]
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:255) ~[jprotobuf-2.2.11.jar:na]
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:234) ~[jprotobuf-2.2.11.jar:na]
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:193) ~[jprotobuf-2.2.11.jar:na]
	at com.baidu.bjf.remoting.protobuf.code.CodedConstant.<clinit>(CodedConstant.java:96) ~[jprotobuf-2.2.11.jar:na]
	... 33 common frames omitted

**Comment by p0mp0k0** [comment]
两年期第一次用，一堆错误，不得已只好从原始proto文件开始；时隔两年再次给个机会用一下把，结果又是不能用，放弃，还是回归proto文件

**Comment by jhunters** [comment]
最新的jdk，需要测试一下。   建议临时办法，加上编译插件，改用jdk 8进行编译。 编译后， 运行在jdk12
