### ISSUE TITLE
java,BigDecial：在一个有注解@ProtobufClass的类中定义一个类型为BigDecimal 的字段。在进行encode的时候报错

### ISSUE THREAD

**Issue by wuchihundan** [jhunters/jprotobuf#158]
环境：
ide:idea 2020.3,
jdk:11.0.9,
maven:3.6.3,
jprotobuf:2.4.7
jprotobuf-precompile-plugin:2.4.4
maven-compiler-plugin:3.8.0
问题描述：
在一个有注解@ProtobufClass的类中定义一个类型为BigDecimal 的字段。在进行encode的时候报：
Exception in thread "main" java.lang.IllegalArgumentException: Class 'java.math.BigDecimal' must has default constructor method with no parameters.
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.getCodeGenerator(ProtobufProxy.java:189)
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:276)
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:249)
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:208)
	at com.baidu.bjf.remoting.protobuf.code.CodedConstant.writeObject(CodedConstant.java:762)
	at com.baidu.bjf.remoting.protobuf.code.CodedConstant.writeObject(CodedConstant.java:739)

**Comment by jhunters** [comment]
增加对BigDecimal与BigInteger类型的支持， 使用方式如下：
    @Protobuf(fieldType = FieldType.BIGDECIMAL)
    public BigDecimal value;
       
    @Protobuf(fieldType = FieldType.BIGINTEGER)
    public BigInteger value2;

由于原生的protobuf本身不支持该类型，同时要保持数据的精度与准备性，在实际序列化与反序化时，使用string类型处理
所以上述的定认，在生成idl方式时，内容会变成如下：
message BigLongPOJO {  
 string value=1;
 string value2=2;
}
