### ISSUE TITLE
Variable "objectPackedDecodeExpress" not defined in template.

### ISSUE THREAD

**Issue by lingfengsan** [jhunters/jprotobuf#164]
Variable "objectPackedDecodeExpress" not defined in template.
com.baidu.bjf.remoting.protobuf.utils.MiniTemplator$VariableNotDefinedException: Variable "objectPackedDecodeExpress" not defined in template.
	at com.baidu.bjf.remoting.protobuf.utils.MiniTemplator.setVariable(MiniTemplator.java:372)
	at com.baidu.bjf.remoting.protobuf.utils.MiniTemplator.setVariable(MiniTemplator.java:388)
	at com.baidu.bjf.remoting.protobuf.code.TemplateCodeGenerator.initDecodeMethodTemplateVariable(TemplateCodeGenerator.java:404)
	at com.baidu.bjf.remoting.protobuf.code.TemplateCodeGenerator.getCode(TemplateCodeGenerator.java:129)
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.doCreate(ProtobufProxy.java:370)
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:311)
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:276)
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:249)
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:208)

**Comment by xiemalin** [comment]
能否补充一下具体case代码吗？

**Comment by lingfengsan** [comment]
> 能否补充一下具体case代码吗？

找到原因了。是因为其它jar报引入了低版本的jprotobuf 配置文件（jprotobuf_classes_template.tql），导致加载了旧的配置文件。建议不兼容的配置通过不同的文件名来区别把
