### ISSUE TITLE
开发环境 springboot  devtools 类加载器 异常

### ISSUE THREAD

**Issue by jianhaozh** [jhunters/jprotobuf#168]
在开发环境下使用jprotobuf和jprotobuf  grpc socket ，springboot  devtools 开启后现类转换异常，是两个类加载器的问题导致，有解决的方法参考么？

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.xxxx.AppRun.main(AppRun.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.ClassCastException: class com.xxxx.vo.CmdResult cannot be cast to class com.xxxx.vo.CmdResult (com.xxxx.vo.CmdResult is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @6764c3a; com.xxxx.vo.CmdResult is in unnamed module of loader 'app')
	at com.xxxx.vo.CmdResult$$JProtoBufClass.encode(CmdResult$$JProtoBufClass.java:24)
	at com.xxxx.modules.storage.SystemRunner.run(SystemRunner.java:109)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795)

**Comment by xiemalin** [comment]
没有在这种场景测试过，看异常的错误，很像是classloader的问题。  devtools是会启动多个classloader吗？ 通过多个cl来解决重加载的问题？

**Comment by wywl99** [comment]
这个问题我今天也碰到了，第一次启动的时候代理类 encode 方法的参数的 Class 是 **AppClassLoader** 加载的，但是未被代理类是 springboot devtools 中的 **RestartClassLoader** 加载的，所以报错了。  

我的解决办法是把 **ClassLoaderImpl** 和 **JavaFileObjectImpl** 这两个类拷出来（都是私有的没办法直接继承），然后写个 **ClassLoaderImpl** 的子类替换掉父加载器为 Spring Boot 的，然后创建个新的 **JdkCompiler** 设置回去 。如下面代码的 `repairJProtobufClassLoader` 方法

还有 build 热加载的时候 springboot devtools 又会重新创建一个新的 RestartClassLoader ，所以也会报错，这里的解决办法是在热加载的时候清除 ProtobufProxy 中的缓存，让代理类重新用新的加载器生成  

代码如下，忽略 ClassLoaderImpl 和 JavaFileObjectImpl 的源码
```java
@Component
public class Repair implements ApplicationListener<ApplicationEvent> {

    public static final class RepairJProtobufAndSpringBootClassLoader extends ClassLoaderImpl{
        /**
         * Instantiates a new class loader impl.
         *
         * @param parentClassLoader the parent class loader
         */
        public RepairJProtobufAndSpringBootClassLoader(ClassLoader parentClassLoader) {
            super(parentClassLoader);
        }
    }

    public static Repair.RepairJProtobufAndSpringBootClassLoader repairJProtobufClassLoader() {
        Repair.RepairJProtobufAndSpringBootClassLoader repairJProtobufAndSpringBootClassLoader = new Repair.RepairJProtobufAndSpringBootClassLoader(Thread.currentThread().getContextClassLoader());
        JdkCompiler jdkCompiler = new JdkCompiler(repairJProtobufAndSpringBootClassLoader);
        JDKCompilerHelper.setCompiler(jdkCompiler);
        return repairJProtobufAndSpringBootClassLoader;
    }

    private static class ClassLoaderImpl extends ClassLoader {
    }

    private static final class JavaFileObjectImpl extends SimpleJavaFileObject {
    }

    @Override
    public void onApplicationEvent(ApplicationEvent event) {
        //热加载的时候会发布 ClassPathChangedEvent 事件，但是这个类导入不了，所以只能这样判断下
        if (event.getClass().getName().contains("ClassPathChangedEvent")){
            ProtobufProxy.clearCache();;
        }
    }
}
```

简单测试了下，可以解决这个问题
