### ISSUE TITLE
List<Date>类型字段预编译报错

### ISSUE THREAD

**Issue by Aliang-code** [jhunters/jprotobuf#207]
## 类代码
```java
public class ApiAccount{
...
@Protobuf
private List<Date> alias_create_time;
...
}
```

##报错信息
```
Caused by: java.lang.IllegalStateException: Compilation failed. class: com.netease.qiye.commons.bean.api.ApiAccount$$JProtoBufClass, diagnostics: [ApiAccount$$JProtoBufClass.java:1739: 错误: 对于add(long), 找不到合适的方法
(ret.getAlias_create_time()).add(input.readInt64());
                            ^
    方法 java.util.Collection.add(java.util.Date)不适用
      (参数不匹配; long无法转换为java.util.Date)
    方法 java.util.List.add(java.util.Date)不适用
      (参数不匹配; long无法转换为java.util.Date), 注: ApiAccount$$JProtoBufClass.java使用了未经检查或不安全的操作。, 注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。, 注: 某些消息已经过简化; 请使用 -Xdiags:verbose 重新编译以获得完整输出]
	at com.baidu.bjf.remoting.protobuf.utils.compiler.JdkCompiler.doCompile(JdkCompiler.java:205)
	at com.baidu.bjf.remoting.protobuf.utils.compiler.AbstractCompiler.compile(AbstractCompiler.java:46)
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.doCreate(ProtobufProxy.java:274)
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:174)
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:155)
	at com.baidu.jprotobuf.mojo.JprotobufPreCompileMain$1.onEntry(JprotobufPreCompileMain.java:134)
	... 14 more
```

**Comment by jhunters** [comment]
List<Date> 类型目前还不支持

**Comment by jhunters** [comment]
2.2.10  版本已支持该功能
