### ISSUE TITLE
预编译报错，JDK版本1.8

### ISSUE THREAD

**Issue by yangzeyi666** [jhunters/jprotobuf#214]
java.lang.NoClassDefFoundError: com/sun/tools/javac/processing/JavacProcessingEnvironment

**Comment by yangzeyi666** [comment]
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at com.baidu.jprotobuf.mojo.PreCompileMojo$1.run (PreCompileMojo.java:326)
    at java.lang.Thread.run (Thread.java:745)
Caused by: jodd.io.findfile.FindFileException: Scan entry error: EntryData{com.example.tools.po.BaseClazz'}; <--- java.lang.IllegalStateException: Compilation failed. class: com.example.tools.po.BaseClazz$$JProtoBufClass, diagnostics: [BaseClazz$$JProtoBufClass.java:24: 警告: Can't initialize javac processor due to (most likely) a class loader problem: java.lang.NoClassDefFoundError: com/sun/tools/javac/processing/JavacProcessingEnvironment
public class BaseClazz$$JProtoBufClass implements com.baidu.bjf.remoting.protobuf.Codec<com.example.tools.po.BaseClazz>, Serializable {
       ^
  	at lombok.javac.apt.LombokProcessor.getJavacProcessingEnvironment(LombokProcessor.java:436)
  	at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:94)
  	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:160)
  	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:213)
  	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:64)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  	at com.baidu.bjf.remoting.protobuf.utils.compiler.JdkCompiler.doCompile(JdkCompiler.java:202)
  	at com.baidu.bjf.remoting.protobuf.utils.compiler.AbstractCompiler.compile(AbstractCompiler.java:46)
  	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.doCreate(ProtobufProxy.java:274)
  	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:174)
  	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:155)
  	at com.baidu.jprotobuf.mojo.JprotobufPreCompileMain$1.onEntry(JprotobufPreCompileMain.java:134)
  	at jodd.io.findfile.ClassFinder.scanEntry(ClassFinder.java:375)
  	at jodd.io.findfile.ClassFinder.scanClassFile(ClassFinder.java:324)
  	at jodd.io.findfile.ClassFinder.scanClassPath(ClassFinder.java:307)
  	at jodd.io.findfile.ClassFinder.scanPath(ClassFinder.java:239)
  	at jodd.io.findfile.ClassFinder.scanPaths(ClassFinder.java:178)
  	at jodd.io.findfile.ClassScanner.scan(ClassScanner.java:35)
  	at jodd.io.findfile.ClassScanner.scanDefaultClasspath(ClassScanner.java:28)
  	at com.baidu.jprotobuf.mojo.JprotobufPreCompileMain.main(JprotobufPreCompileMain.java:182)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at com.baidu.jprotobuf.mojo.PreCompileMojo$1.run(PreCompileMojo.java:326)
, BaseClazz$$JProtoBufClass.java:29: 错误: 找不到符号
        CodecOutputByteArray output = CodecOutputByteArray.get();
        ^
  符号:   类 CodecOutputByteArray
  位置: 类 com.example.tools.po.BaseClazz$$JProtoBufClass, BaseClazz$$JProtoBufClass.java:29: 错误: 找不到符号
        CodecOutputByteArray output = CodecOutputByteArray.get();
                                      ^
  符号:   变量 CodecOutputByteArray
  位置: 类 com.example.tools.po.BaseClazz$$JProtoBufClass]
    at jodd.io.findfile.ClassFinder.scanEntry (ClassFinder.java:377)
    at jodd.io.findfile.ClassFinder.scanClassFile (ClassFinder.java:324)
    at jodd.io.findfile.ClassFinder.scanClassPath (ClassFinder.java:307)
    at jodd.io.findfile.ClassFinder.scanPath (ClassFinder.java:239)
    at jodd.io.findfile.ClassFinder.scanPaths (ClassFinder.java:178)
    at jodd.io.findfile.ClassScanner.scan (ClassScanner.java:35)
    at jodd.io.findfile.ClassScanner.scanDefaultClasspath (ClassScanner.java:28)
    at com.baidu.jprotobuf.mojo.JprotobufPreCompileMain.main (JprotobufPreCompileMain.java:182)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at com.baidu.jprotobuf.mojo.PreCompileMojo$1.run (PreCompileMojo.java:326)
    at java.lang.Thread.run (Thread.java:745)
Caused by: java.lang.Exception: Compilation failed. class: com.example.tools.po.BaseClazz$$JProtoBufClass, diagnostics: [BaseClazz$$JProtoBufClass.java:24: 警告: Can't initialize javac processor due to (most likely) a class loader problem: java.lang.NoClassDefFoundError: com/sun/tools/javac/processing/JavacProcessingEnvironment
public class BaseClazz$$JProtoBufClass implements com.baidu.bjf.remoting.protobuf.Codec<com.example.tools.po.BaseClazz>, Serializable {
       ^
  	at lombok.javac.apt.LombokProcessor.getJavacProcessingEnvironment(LombokProcessor.java:436)
  	at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:94)
  	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:160)
  	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:213)
  	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:64)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  	at com.baidu.bjf.remoting.protobuf.utils.compiler.JdkCompiler.doCompile(JdkCompiler.java:202)
  	at com.baidu.bjf.remoting.protobuf.utils.compiler.AbstractCompiler.compile(AbstractCompiler.java:46)
  	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.doCreate(ProtobufProxy.java:274)
  	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:174)
  	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:155)
  	at com.baidu.jprotobuf.mojo.JprotobufPreCompileMain$1.onEntry(JprotobufPreCompileMain.java:134)
  	at jodd.io.findfile.ClassFinder.scanEntry(ClassFinder.java:375)
  	at jodd.io.findfile.ClassFinder.scanClassFile(ClassFinder.java:324)
  	at jodd.io.findfile.ClassFinder.scanClassPath(ClassFinder.java:307)
  	at jodd.io.findfile.ClassFinder.scanPath(ClassFinder.java:239)
  	at jodd.io.findfile.ClassFinder.scanPaths(ClassFinder.java:178)
  	at jodd.io.findfile.ClassScanner.scan(ClassScanner.java:35)
  	at jodd.io.findfile.ClassScanner.scanDefaultClasspath(ClassScanner.java:28)
  	at com.baidu.jprotobuf.mojo.JprotobufPreCompileMain.main(JprotobufPreCompileMain.java:182)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at com.baidu.jprotobuf.mojo.PreCompileMojo$1.run(PreCompileMojo.java:326)
, BaseClazz$$JProtoBufClass.java:29: 错误: 找不到符号
        CodecOutputByteArray output = CodecOutputByteArray.get();
        ^
  符号:   类 CodecOutputByteArray
  位置: 类 com.example.tools.po.BaseClazz$$JProtoBufClass, BaseClazz$$JProtoBufClass.java:29: 错误: 找不到符号
        CodecOutputByteArray output = CodecOutputByteArray.get();
                                      ^
  符号:   变量 CodecOutputByteArray
  位置: 类 com.example.tools.po.BaseClazz$$JProtoBufClass]
    at com.baidu.jprotobuf.mojo.JprotobufPreCompileMain$1.onEntry (JprotobufPreCompileMain.java:144)
    at jodd.io.findfile.ClassFinder.scanEntry (ClassFinder.java:375)
    at jodd.io.findfile.ClassFinder.scanClassFile (ClassFinder.java:324)
    at jodd.io.findfile.ClassFinder.scanClassPath (ClassFinder.java:307)
    at jodd.io.findfile.ClassFinder.scanPath (ClassFinder.java:239)
    at jodd.io.findfile.ClassFinder.scanPaths (ClassFinder.java:178)
    at jodd.io.findfile.ClassScanner.scan (ClassScanner.java:35)
    at jodd.io.findfile.ClassScanner.scanDefaultClasspath (ClassScanner.java:28)
    at com.baidu.jprotobuf.mojo.JprotobufPreCompileMain.main (JprotobufPreCompileMain.java:182)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at com.baidu.jprotobuf.mojo.PreCompileMojo$1.run (PreCompileMojo.java:326)
    at java.lang.Thread.run (Thread.java:745)
Caused by: java.lang.IllegalStateException: Compilation failed. class: com.example.tools.po.BaseClazz$$JProtoBufClass, diagnostics: [BaseClazz$$JProtoBufClass.java:24: 警告: Can't initialize javac processor due to (most likely) a class loader problem: java.lang.NoClassDefFoundError: com/sun/tools/javac/processing/JavacProcessingEnvironment
public class BaseClazz$$JProtoBufClass implements com.baidu.bjf.remoting.protobuf.Codec<com.example.tools.po.BaseClazz>, Serializable {
       ^
  	at lombok.javac.apt.LombokProcessor.getJavacProcessingEnvironment(LombokProcessor.java:436)
  	at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:94)
  	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:160)
  	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:213)
  	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:64)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  	at com.baidu.bjf.remoting.protobuf.utils.compiler.JdkCompiler.doCompile(JdkCompiler.java:202)
  	at com.baidu.bjf.remoting.protobuf.utils.compiler.AbstractCompiler.compile(AbstractCompiler.java:46)
  	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.doCreate(ProtobufProxy.java:274)
  	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:174)
  	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:155)
  	at com.baidu.jprotobuf.mojo.JprotobufPreCompileMain$1.onEntry(JprotobufPreCompileMain.java:134)
  	at jodd.io.findfile.ClassFinder.scanEntry(ClassFinder.java:375)
  	at jodd.io.findfile.ClassFinder.scanClassFile(ClassFinder.java:324)
  	at jodd.io.findfile.ClassFinder.scanClassPath(ClassFinder.java:307)
  	at jodd.io.findfile.ClassFinder.scanPath(ClassFinder.java:239)
  	at jodd.io.findfile.ClassFinder.scanPaths(ClassFinder.java:178)
  	at jodd.io.findfile.ClassScanner.scan(ClassScanner.java:35)
  	at jodd.io.findfile.ClassScanner.scanDefaultClasspath(ClassScanner.java:28)
  	at com.baidu.jprotobuf.mojo.JprotobufPreCompileMain.main(JprotobufPreCompileMain.java:182)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at com.baidu.jprotobuf.mojo.PreCompileMojo$1.run(PreCompileMojo.java:326)
, BaseClazz$$JProtoBufClass.java:29: 错误: 找不到符号
        CodecOutputByteArray output = CodecOutputByteArray.get();
        ^
  符号:   类 CodecOutputByteArray
  位置: 类 com.example.tools.po.BaseClazz$$JProtoBufClass, BaseClazz$$JProtoBufClass.java:29: 错误: 找不到符号
        CodecOutputByteArray output = CodecOutputByteArray.get();
                                      ^
  符号:   变量 CodecOutputByteArray
  位置: 类 com.example.tools.po.BaseClazz$$JProtoBufClass]
    at com.baidu.bjf.remoting.protobuf.utils.compiler.JdkCompiler.doCompile (JdkCompiler.java:205)
    at com.baidu.bjf.remoting.protobuf.utils.compiler.AbstractCompiler.compile (AbstractCompiler.java:46)
    at com.baidu.bjf.remoting.protobuf.ProtobufProxy.doCreate (ProtobufProxy.java:274)
    at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create (ProtobufProxy.java:174)
    at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create (ProtobufProxy.java:155)
    at com.baidu.jprotobuf.mojo.JprotobufPreCompileMain$1.onEntry (JprotobufPreCompileMain.java:134)
    at jodd.io.findfile.ClassFinder.scanEntry (ClassFinder.java:375)
    at jodd.io.findfile.ClassFinder.scanClassFile (ClassFinder.java:324)
    at jodd.io.findfile.ClassFinder.scanClassPath (ClassFinder.java:307)
    at jodd.io.findfile.ClassFinder.scanPath (ClassFinder.java:239)
    at jodd.io.findfile.ClassFinder.scanPaths (ClassFinder.java:178)
    at jodd.io.findfile.ClassScanner.scan (ClassScanner.java:35)
    at jodd.io.findfile.ClassScanner.scanDefaultClasspath (ClassScanner.java:28)
    at com.baidu.jprotobuf.mojo.JprotobufPreCompileMain.main (JprotobufPreCompileMain.java:182)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at com.baidu.jprotobuf.mojo.PreCompileMojo$1.run (PreCompileMojo.java:326)
    at java.lang.Thread.run (Thread.java:745)
[INFO] JProtobuf pre compile done time took: 1362ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.022 s
[INFO] Finished at: 2024-05-31T09:37:24+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.baidu:jprotobuf-precompile-plugin:2.2.11:precompile (default) on project tools: An exception occured while executing the Java class. null: InvocationTargetException: Scan entry error: EntryData{com.example.tools.po.BaseClazz'}; <--- java.lang.IllegalStateException: Compilation failed. class: com.example.tools.po.BaseClazz$$JProtoBufClass, diagnostics: [BaseClazz$$JProtoBufClass.java:24: 警告: Can't initialize javac processor due to (most likely) a class loader problem: java.lang.NoClassDefFoundError: com/sun/tools/javac/processing/JavacProcessingEnvironment
[ERROR] public class BaseClazz$$JProtoBufClass implements com.baidu.bjf.remoting.protobuf.Codec<com.example.tools.po.BaseClazz>, Serializable {
[ERROR]        ^
[ERROR]   	at lombok.javac.apt.LombokProcessor.getJavacProcessingEnvironment(LombokProcessor.java:436)
[ERROR]   	at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:94)
[ERROR]   	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:160)
[ERROR]   	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:213)
[ERROR]   	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:64)
[ERROR]   	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
[ERROR]   	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
[ERROR]   	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
[ERROR]   	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
[ERROR]   	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
[ERROR]   	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
[ERROR]   	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
[ERROR]   	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
[ERROR]   	at com.sun.tools.javac.main.Main.compile(Main.java:523)
[ERROR]   	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
[ERROR]   	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
[ERROR]   	at com.baidu.bjf.remoting.protobuf.utils.compiler.JdkCompiler.doCompile(JdkCompiler.java:202)
[ERROR]   	at com.baidu.bjf.remoting.protobuf.utils.compiler.AbstractCompiler.compile(AbstractCompiler.java:46)
[ERROR]   	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.doCreate(ProtobufProxy.java:274)
[ERROR]   	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:174)
[ERROR]   	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:155)
[ERROR]   	at com.baidu.jprotobuf.mojo.JprotobufPreCompileMain$1.onEntry(JprotobufPreCompileMain.java:134)
[ERROR]   	at jodd.io.findfile.ClassFinder.scanEntry(ClassFinder.java:375)
[ERROR]   	at jodd.io.findfile.ClassFinder.scanClassFile(ClassFinder.java:324)
[ERROR]   	at jodd.io.findfile.ClassFinder.scanClassPath(ClassFinder.java:307)
[ERROR]   	at jodd.io.findfile.ClassFinder.scanPath(ClassFinder.java:239)
[ERROR]   	at jodd.io.findfile.ClassFinder.scanPaths(ClassFinder.java:178)
[ERROR]   	at jodd.io.findfile.ClassScanner.scan(ClassScanner.java:35)
[ERROR]   	at jodd.io.findfile.ClassScanner.scanDefaultClasspath(ClassScanner.java:28)
[ERROR]   	at com.baidu.jprotobuf.mojo.JprotobufPreCompileMain.main(JprotobufPreCompileMain.java:182)
[ERROR]   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]   	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]   	at com.baidu.jprotobuf.mojo.PreCompileMojo$1.run(PreCompileMojo.java:326)
, BaseClazz$$JProtoBufClass.java:29: 错误: 找不到符号
[ERROR]         CodecOutputByteArray output = CodecOutputByteArray.get();
[ERROR]         ^
[ERROR]   符号:   类 CodecOutputByteArray
[ERROR]   位置: 类 com.example.tools.po.BaseClazz$$JProtoBufClass, BaseClazz$$JProtoBufClass.java:29: 错误: 找不到符号
[ERROR]         CodecOutputByteArray output = CodecOutputByteArray.get();
[ERROR]                                       ^
[ERROR]   符号:   变量 CodecOutputByteArray
[ERROR]   位置: 类 com.example.tools.po.BaseClazz$$JProtoBufClass]
