### ISSUE TITLE
Linux环境下报错，windows环境下正常

### ISSUE THREAD

**Issue by p0mp0k0** [jhunters/jprotobuf#57]
java.lang.ExceptionInInitializerError
        at com.baidu.bjf.remoting.protobuf.ProtobufProxy.doCreate(ProtobufProxy.java:249)
        at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:159)
        at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:126)
        at com.baidu.bjf.remoting.protobuf.CodedConstant.<clinit>(CodedConstant.java:87)
        at com.baidu.bjf.remoting.protobuf.CodeGenerator.getAccessByField(CodeGenerator.java:633)
        at com.baidu.bjf.remoting.protobuf.CodeGenerator.getEncodeMethodCode(CodeGenerator.java:500)
        at com.baidu.bjf.remoting.protobuf.CodeGenerator.getCode(CodeGenerator.java:196)
        at com.baidu.bjf.remoting.protobuf.ProtobufProxy.doCreate(ProtobufProxy.java:224)
        at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:159)
        at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:126)
        at com.novsky.bdds.jms.JMSSender.sendMessage(JMSSender.java:54)
        at com.novsky.bdds.utility.DeviceOnlineCheckerUtil.registerDeviceOnlineChecker(DeviceOnlineCheckerUtil.java:51)
        at com.novsky.bdds.business.StarTrackerTrackerRecieverCMD.V4(StarTrackerTrackerRecieverCMD.java:164)
        at com.novsky.bdds.business.StarTrackerTrackerRecieverCMD.process(StarTrackerTrackerRecieverCMD.java:51)
        at com.novsky.bdds.deviceservice.StarTrackerCmdHandler.channelRead0(StarTrackerCmdHandler.java:58)
        at com.novsky.bdds.deviceservice.StarTrackerCmdHandler.channelRead0(StarTrackerCmdHandler.java:30)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:288)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
        at com.novsky.bdds.deviceservice.StarTrackerBytesToDataListDecoder.channelRead(StarTrackerBytesToDataListDecoder.java:76)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1336)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:544)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: compiler is null maybe you are on JRE enviroment please change to JDK enviroment.
        at com.baidu.bjf.remoting.protobuf.utils.compiler.JdkCompiler.<init>(JdkCompiler.java:90)
        at com.baidu.bjf.remoting.protobuf.utils.compiler.JdkCompiler.<init>(JdkCompiler.java:80)
        at com.baidu.bjf.remoting.protobuf.utils.JDKCompilerHelper.<clinit>(JDKCompilerHelper.java:32)
        ... 49 more

**Comment by jhunters** [comment]
请切到 jdk环境下运行

**Comment by p0mp0k0** [comment]
拜托，麻烦好好想想，我要编写程序编译，能没有JDK吗？

**Comment by jhunters** [comment]
可以使用预编译方式，运行就只需要jre即可，参见 https://github.com/jhunters/jprotobuf/issues/39

**Comment by p0mp0k0** [comment]
看了39，这个是在使用maven环境下解决方案，没有使用maven的项目如何解决这个问题呢？

**Comment by jhunters** [comment]
ProtobufProxy增加生成中间编译java字节码文件功能

使用示例：

ProtobufProxy.create(AddressBookProtosPOJO.class, false, new File("D:/"));

ProtobufIDLProxy.create(string, false， new File("D:/"));
上面的示例，则会直接把生成的中间子节码文件生成到D盘根目录下。

注：目前ProtobufIDLProxy已经能完全支持含有内部类或内部枚举类型的message的动态解析。

**Comment by yangqianghui** [comment]
问题具体怎么解决，现在非maven项目也遇到了。一年过去了，光吵吵，就没有一个解决方案吗？

**Comment by yangqianghui** [comment]
刚刚检查了一下配置，修改一下JDK的环境配置，尤其是java自动升级安装后，会自动添加一条C:\ProgramData\Oracle\Java\javapath;要去掉。保留我们自己配置的%JAVA_HOME%\bin;。
JAVA_HOME如下：
![snipaste_2017-11-01_14-16-38](https://user-images.githubusercontent.com/11780337/32262456-b96edee6-bf0f-11e7-96d3-8a53b5ec8d7b.png)

Path如下：
**%JAVA_HOME%\bin;**%GRADLE_HOME%\bin;%MAVEN_HOME%\bin;%ANDROID_SDK_HOME%/tools;%ANDROID_SDK_HOME%/platform-tools;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\

**Comment by jhunters** [comment]
是说jdk环境下仍不能工作吗？
