### ISSUE TITLE
Protobuf v3的支持

### ISSUE THREAD

**Issue by Lonecy** [jhunters/jprotobuf#64]
我用V3 下通过proto生成java时报以下错误， 是不支持V3 吗?

Exception in thread "main" java.lang.IllegalStateException: Syntax error in ****proto\test.proto at 7:11: unexpected label: int32
	at com.squareup.protoparser.ProtoParser.unexpected(ProtoParser.java:948)
	at com.squareup.protoparser.ProtoParser.readDeclaration(ProtoParser.java:197)
	at com.squareup.protoparser.ProtoParser.readMessage(ProtoParser.java:219)
	at com.squareup.protoparser.ProtoParser.readDeclaration(ProtoParser.java:153)
	at com.squareup.protoparser.ProtoParser.readProtoFile(ProtoParser.java:92)
	at com.squareup.protoparser.ProtoParser.parse(ProtoParser.java:56)
	at com.squareup.protoparser.ProtoParser.parseUtf8(ProtoParser.java:45)
	at com.squareup.protoparser.ProtoParser.parseUtf8(ProtoParser.java:32)
	at com.baidu.bjf.remoting.protobuf.ProtobufIDLProxy.findRelateProtoFiles(ProtobufIDLProxy.java:512)
	at com.baidu.bjf.remoting.protobuf.ProtobufIDLProxy.doCreatePro(ProtobufIDLProxy.java:381)
	at com.baidu.bjf.remoting.protobuf.ProtobufIDLProxy.generateSource(ProtobufIDLProxy.java:287)
	at com.baidu.bjf.remoting.protobuf.ProtobufIDLProxy.generateSource(ProtobufIDLProxy.java:281)

**Comment by jhunters** [comment]
使用的版本是2.x吗？ 把proto文件完整发一下出来吧

**Comment by Lonecy** [comment]
syntax = "proto3";
package aa;

message Person {

    // ID
    int32 id = 1;

    // 姓名
    string name = 2;

    // email
    string email = 3;

    // 朋友
    string friends = 4;

    map<string, string> projects = 5;
    Result result = 6;

}

message Result {

    int32 code = 1;

    string msg = 2;

}

**Comment by Lonecy** [comment]
用的是  https://github.com/jhunters/jprotobuf/tree/master/v3  这里的代码编译。
发现我加个optional  就可以编译过了。但 ptotobuf v3 已经弃用了optional 和required.
能否增加对V3的支持

**Comment by jhunters** [comment]
fix version 2.0.5
