### ISSUE TITLE
jprotobuf是不支持extensions 100 to max这种扩展吗?

### ISSUE THREAD

**Issue by zhoujie950711** [jhunters/jprotobuf#78]
message Base {
  	optional int32 cmd = 1;       
  	optional int32 code = 2;
  	optional string token = 4;
  	optional string key = 5;
  	extensions 100 to max; 
}

message PropBehaviorRq{
  optional string time = 1;// 查询时间
  repeated string Server = 2;// 区服Id
  optional int32 ranking = 3;// 排名等级
  optional int32 getCode = 4;// 行为
  repeated string prop = 5;// 道具Id
  repeated string extension = 6;// 扩展
  extend Base
    {
      optional PropBehaviorRq ext = 204;
    }
}

通过.proto文件生成的java类,是没有extensions

**Comment by jhunters** [comment]
暂不支持该功能，后续会考虑进来

**Comment by zhoujie950711** [comment]
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/baidu/bjf/remoting/protobuf/CodedConstant.computeElementSizeNoTag(Lcom/google/protobuf/WireFormat$FieldType;Ljava/lang/Object;)I @292: invokestatic
  Reason:
    Type 'com/google/protobuf/LazyField' (current frame, stack[0]) is not assignable to 'com/google/protobuf/LazyFieldLite'
  Current Frame:
    bci: @292
    flags: { }
    locals: { 'com/google/protobuf/WireFormat$FieldType', 'java/lang/Object' }
    stack: { 'com/google/protobuf/LazyField' }
  Bytecode:
    0x0000000: b200 e02a b600 e12e aa00 0000 0000 016a
    0x0000010: 0000 0001 0000 0012 0000 0058 0000 0063
    0x0000020: 0000 006e 0000 0079 0000 0084 0000 008f
    0x0000030: 0000 009a 0000 00a5 0000 00b0 0000 00c0
    0x0000040: 0000 00da 0000 00e5 0000 00f0 0000 00fb
    0x0000050: 0000 0106 0000 00b8 0000 0111 0000 0125
    0x0000060: 2bc0 00b2 b600 87b8 0088 ac2b c000 bbb6
    0x0000070: 009a b800 9bac 2bc0 00b8 b600 96b8 0097
    0x0000080: ac2b c000 b8b6 0096 b801 07ac 2bc0 00b5
    0x0000090: b600 8fb8 005d ac2b c000 b8b6 0096 b801
    0x00000a0: 08ac 2bc0 00b5 b600 8fb8 0109 ac2b c000
    0x00000b0: adb6 007f b800 80ac 2bc0 00d6 b800 7cac
    0x00000c0: 2bc0 00fb b801 0aac 2bc1 0102 9900 0b2b
    0x00000d0: c001 02b8 0083 ac2b c000 81c0 0081 b801
    0x00000e0: 0bac 2bc0 00b5 b600 8fb8 0106 ac2b c000
    0x00000f0: b5b6 008f b801 0cac 2bc0 00b8 b600 96b8
    0x0000100: 010d ac2b c000 b5b6 008f b801 0eac 2bc0
    0x0000110: 00b8 b600 96b8 010f ac2b c101 1099 000b
    0x0000120: 2bc0 0110 b801 11ac 2bb8 0112 ac2b c101
    0x0000130: 0499 0010 2bc0 0104 b901 0501 00b8 0113
    0x0000140: ac2b c100 3599 0010 2bc0 0035 b900 9c01
    0x0000150: 00b8 0113 ac2b c100 4599 000e 2bc0 0045
    0x0000160: b600 9db8 0113 ac2b c000 b5b6 008f b801
    0x0000170: 13ac bb00 7759 12f9 b700 fabf          
  Stackmap Table:
    same_frame_extended(@96)
    same_frame(@107)
    same_frame(@118)
    same_frame(@129)
    same_frame(@140)
    same_frame(@151)
    same_frame(@162)
    same_frame(@173)
    same_frame(@184)
    same_frame(@192)
    same_frame(@200)
    same_frame(@215)
    same_frame(@226)
    same_frame(@237)
    same_frame(@248)
    same_frame(@259)
    same_frame(@270)
    same_frame(@281)
    same_frame(@296)
    same_frame(@301)
    same_frame(@321)
    same_frame(@341)
    same_frame(@359)
    same_frame(@370)


	at com.baidu.bjf.remoting.protobuf.CodeGenerator.getAccessByField(CodeGenerator.java:669)
	at com.baidu.bjf.remoting.protobuf.CodeGenerator.getEncodeMethodCode(CodeGenerator.java:536)
	at com.baidu.bjf.remoting.protobuf.CodeGenerator.getCode(CodeGenerator.java:198)
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.doCreate(ProtobufProxy.java:239)
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:173)
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:140)
	at com.hundredcent.console.pb.test.BaseTest.test(BaseTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

当我集成到自己的项目时候,报这个错误
