### ISSUE TITLE
使用@JmsListener监听消息队列，执行jprotobuf的encode、decode方法报错

### ISSUE THREAD

**Issue by zhangviv** [jhunters/jprotobuf#83]

**Comment by jhunters** [comment]
具体的错误信息呢？

**Comment by zhangviv** [comment]
017-12-27 09:50:48.594 WARN  --- [listenerContainer-1]  org.springframework.jms.listener.DefaultMessageListenerContainer invokeErrorHandler 936 - Execution of JMS message listener failed, and no ErrorHandler has been set.
java.lang.ClassCastException: com.ynt.ai.activemq.protobuf.MsgHeader cannot be cast to com.ynt.ai.activemq.protobuf.MsgHeader
	at com.ynt.ai.activemq.QueueMessageListener.onMessage(QueueMessageListener.java:27)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:317)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:255)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1166)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1158)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1055)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jhunters** [comment]
这个信息 没有看到与jprotobuf有什么关系?

**Comment by zhangviv** [comment]
很奇怪，如果是在消息监听里面执行jprotobuf的encode，decode方法就会报错；我用的是activemq，如果在类里面写一个main方法或者在test测试类里都没有问题。
报错的代码如下：当执行 headerCodec.decode(bytes64)时就会报错
`  consumer.setMessageListener(new MessageListener() {
            public void onMessage(Message message) {
                TextMessage textMessage= (TextMessage) message;
                try {
                    String msg = "CAEQ6AcY6QcgAg==";
                    byte[] bytes64 = CommonUtil.base64Decode(msg);
                    Codec<MsgHeader> headerCodec = ProtobufProxy.create(MsgHeader.class);
                    MsgHeader msgHeader = null;
                    try {
                        msgHeader = headerCodec.decode(bytes64);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    System.out.println(msgHeader.msgType.value());
                    System.out.println("接收消息:"+textMessage.getText());
                } catch (JMSException e) {
                    e.printStackTrace();
                }
            }
        });`

**Comment by jhunters** [comment]
不确定是不是 jprotobuf引起的，你如果在onMessage里把jprotobuf的处理代理移除，看看是不是也一样报错?

**Comment by zhangviv** [comment]
其他的接受消息，处理没什么问题的。，之前我是用的protobuf自带的工具生成java类，然后用protobuf的内部类去反序列化对象的，后面有人推荐了百度的这个jprotobuf，我就使用看看。发现有问题，一开始我以为是@JmsListener注解的问题，后来试了原始的jms的写法，就刚刚发的，一样有问题。下面是protobuf的生成的Java类的写法，没问题。
 byte[] bytes64 = CommonUtil.base64Decode(textMessage);
        MsgContext.MsgHeader msgHeader = null;
        try {
            msgHeader = MsgContext.MsgHeader.parseFrom(bytes64);
            log.info(String.valueOf(msgHeader.getOpCode().getNumber()));
        } catch (InvalidProtocolBufferException e) {
            e.printStackTrace();
        }

**Comment by jhunters** [comment]
那的确有些奇怪，未遇到过此类情况。  如果main执行没有问题，应该也是能常工作的，最奇怪的是这个情况 java.lang.ClassCastException: com.ynt.ai.activemq.protobuf.MsgHeader cannot be cast to com.ynt.ai.activemq.protobuf.MsgHeader。 相同的类为什么不能转换？  MsgHeader在你那边是有多个吗？

**Comment by zhangviv** [comment]
是比较奇怪的报错信息，我试过其他的简单类，如下：
public class TestProto {

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Protobuf(fieldType = FieldType.STRING, order = 1, required = true)
    public String name;
    @Protobuf(fieldType = FieldType.INT32, order = 2, required = true)
    public Integer id;
}
结果一样报错，
java.lang.ClassCastException: com.ynt.ai.activemq.protobuf.TestProto cannot be cast to com.ynt.ai.activemq.protobuf.TestProto
还有个问题，pom里是不是引用这个包就可以了
		
		<dependency>
			<groupId>com.baidu</groupId>
			<artifactId>jprotobuf</artifactId>
			<version>2.1.4</version>
		</dependency>

**Comment by jhunters** [comment]
pom引用这个就可以了。  你上面的代码我这边运行都是正常的

**Comment by zhangviv** [comment]
那我再看看吧

**Comment by zhangviv** [comment]
已解决，个人代码问题，后来排查出来了，由于项目引用了热部署的包导致的，注释掉就可以了，难怪会提示类不能转换成类自己呢。
