### ISSUE TITLE
解析protobuf3 map类型出错

### ISSUE THREAD

**Issue by dongjiaqiang** [jhunters/jprotobuf#92]
```java
String schema="syntax = \"proto3\";\n" +
                "\n" +
                "package tutorial;\n" +
                "\n" +
                "option java_package = \"com.ximalaya.recsys.feature.model\";\n" +
                "\n" +
                "message UserFeature{\n" +
                "   string userId = 1 ;\n" +
                "   int64 version = 2 ;\n" +
                "   repeated double feature = 3;\n" +
                "   repeated Vector vector = 4;\n" +
                "}\n" +
                "\n" +
                "message AlbumFeature{\n" +
                "   int64 albumId = 1;\n" +
                "   int64 version = 2;\n" +
                "   map<string,Vector> vectorMap =3;\n" +
                "   repeated double feature = 4;\n" +
                "}\n" +
                "\n" +
                "message Vector{\n" +
                "   repeated double vector = 1;\n" +
                "}";

 Map<String,IDLProxyObject> map=ProtobufIDLProxy.create(schema);
```
  schema中定义了一个map value字段类型为自定义类型 会提示该类型找不到 版本为2.2.4
```java
java.lang.RuntimeException: Compilation failed. class: com.ximalaya.recsys.feature.model.AlbumFeatureJProtoBufProtoClassd5a22cb19b0143f794354bb5f2f4213a, diagnostics: [AlbumFeatureJProtoBufProtoClassd5a22cb19b0143f794354bb5f2f4213a.java:12: 错误: 找不到符号
public java.util.Map<String, Vector> vectorMap;
                             ^
  符号:   类 Vector
  位置: 类 com.ximalaya.recsys.feature.model.AlbumFeatureJProtoBufProtoClassd5a22cb19b0143f794354bb5f2f4213a]

	at com.baidu.bjf.remoting.protobuf.ProtobufIDLProxy.create(ProtobufIDLProxy.java:559)
	at com.baidu.bjf.remoting.protobuf.ProtobufIDLProxy.create(ProtobufIDLProxy.java:517)
	at com.baidu.bjf.remoting.protobuf.ProtobufIDLProxy.create(ProtobufIDLProxy.java:506)
	at com.ximalaya.recsys.pb.TestJProtocolBuf.test3(TestJProtocolBuf.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalStateException: Compilation failed. class: com.ximalaya.recsys.feature.model.AlbumFeatureJProtoBufProtoClassd5a22cb19b0143f794354bb5f2f4213a, diagnostics: [AlbumFeatureJProtoBufProtoClassd5a22cb19b0143f794354bb5f2f4213a.java:12: 错误: 找不到符号
public java.util.Map<String, Vector> vectorMap;
```

**Comment by jhunters** [comment]
2.2.5-SNAPSHOT 修复了该问题

**Comment by dongjiaqiang** [comment]
我使用你修复后的jar后 跑这个单元测试会报错
```java
 @Test
    public void test11()throws Exception{

        String schema="syntax = \"proto3\";\n" +
                "\n" +
                "package tutorial;\n" +
                "\n" +
                "option java_package = \"com.ximalaya.recsys.feature.model\";\n" +
                "\n" +
                "message TEST_MSM{\n" +
                "   string field1 = 1 ;\n" +
                "   int64 field2 = 2 ;\n" +
                "   float field3 = 3;\n" +
                "   map<int32,Vector> map = 4;\n" +
                "}\n" +
                "\n" +
                "message TEST_MSS{\n" +
                "    string field4 = 1;\n" +
                "    repeated Vector vector = 2;\n" +
                "}\n" +
                "\n" +
                "message Vector{\n" +
                "   repeated double vector = 1;\n" +
                "}";

        Map<String,IDLProxyObject> map=ProtobufIDLProxy.create(schema);
        IDLProxyObject idlProxyObject=map.get("TEST_MSM").newInstnace();

        idlProxyObject.put("field1","1212");
        idlProxyObject.put("field2",12121L);
        idlProxyObject.put("field3",1.3f);

        IDLProxyObject idlProxyObject1 = map.get("Vector").newInstnace();
        idlProxyObject1.put("vector",Lists.newArrayList(1.2,3.2));

        Map map1 = Maps.newHashMap();
        map1.put(12,idlProxyObject1);

        idlProxyObject.put("map",map1);

        idlProxyObject.encode();

    }
```

```
java.lang.IllegalArgumentException: Class 'com.baidu.bjf.remoting.protobuf.IDLProxyObject' must has default constructor method with no parameters.

	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.getCodeGenerator(ProtobufProxy.java:125)
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:208)
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:149)
	at com.baidu.bjf.remoting.protobuf.CodedConstant.computeObjectSizeNoTag(CodedConstant.java:485)
	at com.baidu.bjf.remoting.protobuf.CodedConstant.computeElementSizeNoTag(CodedConstant.java:1264)
	at com.baidu.bjf.remoting.protobuf.CodedConstant.computeElementSize(CodedConstant.java:116)
	at com.baidu.bjf.remoting.protobuf.MapEntryLite.computeSerializedSize(MapEntryLite.java:187)
	at com.baidu.bjf.remoting.protobuf.MapEntry.getSerializedSize(MapEntry.java:196)
	at com.google.protobuf.CodedOutputStream.computeMessageSizeNoTag(CodedOutputStream.java:903)
	at com.google.protobuf.CodedOutputStream.computeMessageSize(CodedOutputStream.java:656)
	at com.baidu.bjf.remoting.protobuf.CodedConstant.computeMapSize(CodedConstant.java:386)
	at com.ximalaya.recsys.feature.model.TEST_MSMJProtoBufProtoClass329f6e2b55104c3b8323b98b22d90c7d$$JProtoBufClass.encode(TEST_MSMJProtoBufProtoClass329f6e2b55104c3b8323b98b22d90c7d$$JProtoBufClass.java:41)
	at com.ximalaya.recsys.feature.model.TEST_MSMJProtoBufProtoClass329f6e2b55104c3b8323b98b22d90c7d$$JProtoBufClass.encode(TEST_MSMJProtoBufProtoClass329f6e2b55104c3b8323b98b22d90c7d$$JProtoBufClass.java:9)
	at com.baidu.bjf.remoting.protobuf.IDLProxyObject.encode(IDLProxyObject.java:328)
	at com.ximalaya.recsys.pb.TestDeserializer.test11(TestDeserializer.java:281)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NoSuchMethodException: com.baidu.bjf.remoting.protobuf.IDLProxyObject.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.getCodeGenerator(ProtobufProxy.java:122)
	... 36 more


```
